### ISSUE TITLE
Not working with 'node-full-text-search-light' 

### ISSUE THREAD

**Issue by airsidemap** [aacerox/node-rest-client#146]
Hello
The modul is not working combined with 'node-full-text-search-light'. 
If fulltextsearchlight is loaded bevor node-rest-client, the following error occurs at startup: 
```
C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:10
var propType  = props[propIndex].split(":");

TypeError: props[propIndex].split is not a function
    at validateProperties (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:10:39)
    at Object.validate (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:21:13)
    at ParserManager.add (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:34:17)
    at module.exports (C:\Daten\aaa\node_modules\node-rest-client\lib\nrc-parser-manager.js:112:15)
    at new exports.Client (C:\Daten\aaa\node_modules\node-rest-client\lib\node-rest-client.js:12:53)
    at Object.<anonymous> (C:\Daten\aaa\index.js:15:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

If fulltextsearchlight is loaded after node-rest-client, the program starts normal, but the output of node-rest-client is somehow corrupted.

**Comment by aacerox** [comment]
Hi
the problem is with this part of code in node-full-text-search-light at the beginning of the index.js file:
```javascript
Array.prototype.unique = function () {
    var a = [];
    for (var i = 0, l = this.length; i < l; i++) {
        if (a.indexOf(this[i]) === -1) {
            a.push(this[i]);
        }
    }
    return a;
};
```
Adding methods to Array.prototype it's not a good idea because that method will added to every array as an element and will be iterated in every "for ..in" over  *every array* created after method prototype declaration.

please refer to this  [StackOverflow question](http://stackoverflow.com/questions/948358/adding-custom-functions-into-array-prototype) for more details
