### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by FranzZemen** [aacerox/node-rest-client#79]
This is a warning that an EventEmitter instance has more than the configured listeners set.  By default that's 10 with node.

I have some client wrapper classes that call node-rest-client.  One in particular is an authentication client.  

The "core" services I access through REST all call the auth client first.  Given that there are multiple core service calls per module functionality, the auth client can get called more than 10x while serving a user request, each going further down the promise chain.  This means that node-rest-client can ultimately be invoked many times before everything unwinds.   

I'm pretty sure the Event Emitter warning (and associated stack trace shown below) occurs in node-rest-client but can't figure out how to increase its event emitter listener configuration.

Trace
    at Object.addListener (events.js:179:15)
    at new exports.Client (E:\src\clients\client1\ztarmobile\rest\node_modules\node-rest-client\lib\node-rest-client.js:326:17)
    at RestClientBase.rest (E:\src\clients\client1\ztarmobile\rest\server\components\rest-client\RestClientBase.js:154:30)
    at RestClientBase.AuthClient.authorizeResource (E:\src\clients\client1\ztarmobile\rest\server\components\rest-client\AuthClient.js:52:21)
    at Object.module.exports.authorizeProductCatalogEntry (E:\src\clients\client1\ztarmobile\rest\server\components\service\authorize.service.js:14:27)
    at E:\src\clients\client1\ztarmobile\rest\server\components\service\authorize.service.js:45:47
    at _fulfilled (e:\src\clients\client1\components\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (e:\src\clients\client1\components\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (e:\src\clients\client1\components\node_modules\q\q.js:756:13)
    at e:\src\clients\client1\components\node_modules\q\q.js:564:44

**Comment by FranzZemen** [comment]
By the way...the confusing thing is that it doesn't always happen.  There's a timing component to it that I'm guessing is related to responses from the server.

**Comment by FranzZemen** [comment]
The problem is with ConnectManager when it registers an error handler, within the Client function.  

I may be wrong, but it really does look like a memory leak.It seems the more rest clients created the more listeners created, with no cleanup.  I'm using node-rest-client Client as a locally created variable for every call.  Thus, an error listener is added for every call, but I can't see how its being removed.

**Comment by FranzZemen** [comment]
The problem is with ConnectManager when it registers an error handler, within the Client function.  Not sure if there's a memory leak here...it kind of looks like it since ConnectManager does not de-register the event handler, and its a module instance variable.

**Comment by FranzZemen** [comment]
There is indeed a memory leak.  I've created a new thread for it:

https://github.com/aacerox/node-rest-client/issues/80

Closing this one:
