### ISSUE TITLE
'indexOf' issue

### ISSUE THREAD

**Issue by harsha47** [aacerox/node-rest-client#88]
hey,
I am trying to query json from api call, and write that json to a file, i am getting the following error message
Please have a look,
Thank you.

/var/www/mobile2/node_modules/node-rest-client/lib/node-rest-client.js:74
                                protocol = url.protocol.indexOf(":") == -1?url.protocol:url.protocol.subst
                                                        ^
TypeError: Cannot call method 'indexOf' of null
    at Object.Util.createConnectOptions (/var/www/mobile2/node_modules/node-rest-client/lib/node-rest-client.js:74:29)
    at Object.Util.connect (/var/www/mobile2/node_modules/node-rest-client/lib/node-rest-client.js:190:23)
    at get (/var/www/mobile2/node_modules/node-rest-client/lib/node-rest-client.js:286:8)
    at /var/www/mobile2/generateMenu.js:17:9
    at Object.<anonymous> (/var/www/mobile2/generateMenu.js:30:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by szikszail** [comment]
@harsha47 could you include an URL with the code throw this error?
As I think NodeJS's URL module's parse method could not recognize your URL's protocol, so it returned nothing in the `protocol` field.

**Comment by harsha47** [comment]
@szikszail thank you for replying, the url was correct, the issue was with the user permission  to make a url call on my instance box.
After running with correct user permissions it worked just fine.
